name: kirky-run-python-updated
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '0 18 * * *' # Run at 18:00 UTC daily (4am QLD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      
      - name: Install Python Packages
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: python redgatedownload.py
      
      - name: Commit Files
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
        
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
